//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstEntFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int VendorID { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string ContactLName { get; set; }
        public string ContactFName { get; set; }
        public int DefaultTermsID { get; set; }
        public int DefaultAccountNo { get; set; }
    
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
